src/Entity/ListeExcuse.php
<?php

namespace App\Entity;

use App\Repository\ListeExcuseRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ListeExcuseRepository::class)]
class ListeExcuse
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $http_code = null;

    #[ORM\Column(length: 255)]
    private ?string $tag = null;

    #[ORM\Column(length: 255)]
    private ?string $message = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getHttpCode(): ?int
    {
        return $this->http_code;
    }

    public function setHttpCode(int $http_code): static
    {
        $this->http_code = $http_code;

        return $this;
    }

    public function getTag(): ?string
    {
        return $this->tag;
    }

    public function setTag(string $tag): static
    {
        $this->tag = $tag;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): static
    {
        $this->message = $message;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\ListeExcuseRepository;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(ListeExcuseRepository $excuseRepository): Response
    {
        // Récupérer une excuse au hasard depuis le repository
        $excuse = $excuseRepository->getRandomExcuse();

        return $this->render('home/index.html.twig', [
            'excuse' => $excuse,
        ]);
    }

    #[Route('/export', name: 'app_export')]
    public function exportData(ListeExcuseRepository $excuseRepository): Response
    {
    // Récupérer toutes les excuses depuis le repository
    $excuses = $excuseRepository->findAll();

    // Créer un tableau avec les en-têtes des colonnes
    $csvData = [
        ['ID', 'HTTP Code', 'Tag', 'Message']
    ];

    // Remplir le tableau avec les données des excuses
    foreach ($excuses as $excuse) {
        $csvData[] = [
            $excuse->getId(),
            $excuse->getHttpCode(),
            $excuse->getTag(),
            $excuse->getMessage()
        ];
    }

    // Créer un fichier CSV temporaire
    $tempFilePath = tempnam(sys_get_temp_dir(), 'excuses_');
    $handle = fopen($tempFilePath, 'w');
    foreach ($csvData as $line) {
        fputcsv($handle, $line);
    }
    fclose($handle);

    // Envoyer le fichier CSV en tant que réponse
    return $this->file($tempFilePath, 'excuses.csv');
}

}

src/Controller/HttpCodeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use App\Repository\ListeExcuseRepository;

class HttpCodeController extends AbstractController
{
    #[Route('/http/code', name: 'app_http_code')]
    public function index(ListeExcuseRepository $excuseRepository): Response
    {
         // Récupérer une excuse au hasard depuis le repository
         $excuse = $excuseRepository->getRandomExcuse();
        return $this->render('http_code/code.html.twig', [
            'excuse' => $excuse,
        ]);
    }
}

src/Controller/LostController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class LostController extends AbstractController
{
    #[Route('/lost', name: 'app_lost')]
    public function index(): Response
    {
        //retourne la page lost
        return $this->render('lost/lost.html.twig', [
            'controller_name' => 'LostController',
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
        {% block stylesheets %}
        {% endblock %}

        {% block javascripts %}
            {% block importmap %}{{ importmap('app') }}{% endblock %}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/bundles/TwigBundle/Exception/error404.html.twig
{# templates/error404.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Page introuvable{% endblock %}

{% block body %}
<body class="d-flex justify-content-center align-items-center vh-100">
    <div class="text-center">
        <h1>Oops! Page introuvable</h1>
        <p>Désolé, la page que vous recherchez est introuvable.</p>
        <a href="{{ path('app_home') }}">retour a la page accueil</a>
    </div>
</body>
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block header %}

{% endblock %}

{% block body %}

<body class="d-flex justify-content-center align-items-center vh-100">
    <div class="text-center">
        <h1>Excuse du jour :</h1>
        <p>{{ excuse.message }}</p>
        <a href="{{ path('app_http_code', {'code': excuse.httpCode}) }}" class="btn btn-primary">
            Générer une Excuse
        </a>

        {# Ajout du bouton pour exporter les données #}
        <a href="{{ path('app_export') }}" class="btn btn-secondary">
            Exporter les données
        </a>
    </div>
</body>

{% endblock %}

templates/http_code/code.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page Erreur{{ excuse.httpCode }} {% endblock %}

{% block body %}

<body class="d-flex justify-content-center align-items-center vh-100">
    <div class="text-center">
        <p>Erreur {{ excuse.httpCode }}</p>
        <p>{{ excuse.tag }}</p>
        <p>{{ excuse.message }}</p>
       <a href="{{ path('app_home') }}">retour a la page accueil</a>
    </div>
</body>

{% endblock %}

templates/http_code/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page Erreur{{ excuse.httpCode }} {% endblock %}

{% block body %}

<body class="d-flex justify-content-center align-items-center vh-100">
    <div class="text-center">
        <p>Erreur {{ excuse.httpCode }}</p>
        <p>{{ excuse.tag }}</p>
        <p>{{ excuse.message }}</p>
       <a href="{{ path('app_home') }}">retour a la page accueil</a>
    </div>
</body>

{% endblock %}

templates/lost/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Je suis perdu{% endblock %}

{% block body %}
<body class="d-flex justify-content-center align-items-center vh-100">

    <div class="text-center">
        <h1>Je suis perdu</h1>
        <img src="img/2rM.gif" class="img-fluid">
        <p>Vous serez redirigé vers la page d'accueil dans 5 secondes...</p>
    </div>

    <script>
        setTimeout(function() {
            // Rediriger vers une autre page après 5 secondes en utilisant l'URL générée par Symfony
            window.location.href = "{{ path('app_home') }}";
        }, 5000); // 5000 ms = 5 secondes
    </script>
</body>
  
{% endblock %}

templates/lost/lost.html.twig
{% extends 'base.html.twig' %}

{% block title %}Je suis perdu{% endblock %}

{% block body %}
<body class="d-flex justify-content-center align-items-center vh-100">

    <div class="text-center">
        <h1>Je suis perdu</h1>
        <img src="img/2rM.gif" class="img-fluid">
        <p>Vous serez redirigé vers la page d'accueil dans 5 secondes...</p>
    </div>

    <script>
        setTimeout(function() {
            // Rediriger vers une autre page après 5 secondes en utilisant l'URL générée par Symfony
            window.location.href = "{{ path('app_home') }}";
        }, 5000); // 5000 ms = 5 secondes
    </script>
</body>
  
{% endblock %}